version: "3.9"

services:
    php:
        build: .
        container_name: '${APP_NAME}-server'
        ports:
            - '${SERVER_PORT}:80'
        volumes:
            - .:/var/www/html:cached
            - /var/www/html/var
            - /var/www/html/vendor
        depends_on:
            - db

    db:
        image: postgres:16
        container_name: '${APP_NAME}-db'
        environment:
            POSTGRES_DB: "${POSTGRES_DB:-postgres}"
            POSTGRES_USER: '${POSTGRES_USER:-user}'
            POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-password}'
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
